language: python
cache: pip
python:
- pypy3
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 3.7-dev
- 3.8-dev
install:
- pip install -r requirements.txt
script:
- python test.py
before_deploy:
  - rm -rfv ./build ./dist
deploy:
  - provider: pypi
    user: arthuro555
    password:
      secure: NFB02DkSh4U8Gy+o+gInJYTBDTBY18D/XF9+BbOa6LqfF7kNbkYwBpFe2Q3gk7gz6H0536/tMOc4fk2xe/Gu8FCkI726UC4UMOcAfOuI5pZGz8rkkQ8lI1/D/PRxhp83KPfQx+7qJ2RzmiMLZSOGJAuYPOVoLBillYanOze6X3rZ/LcrkrhpT5umA9QRO2X+vgPOwsQGBOyIg898OUqfvJ4ddxsgpUm6V9ZPZa1Xl0TFb3SXTUt3+iIv0aVr+GsPrceXvbh1y8EAtbiMlbZysxK0Ci45h44rjO8w8dWs9jwey/MBuZCd1PUlD8OOxgI3cVyD8q7n+TGDVawgPKKXj/sChGH4mchS8mKS8UcSf8MM1dro9DTK8CuPSQ9Un4RIIsmSXeDODkZ1729sMc0h8RRM5bIjlVt3n1KQYzJK9w9tlWEyrLNUUH42yhOdqBqzMdQSO6yDJ7oE7MV3Q2OfG3BHXeyBCrzn8N5IUZDhXuD9Es3b7Jg8wOWY8DfX/fvxYivVnNK0meVGv71Rj9ldgt/HgMyEQXnepS/FJ3/1qRSEBMMr/7npKYMC6n7S5adrIOPRW8Zc7v1J1ZB27xs+y9OdlVuCSOA0Z/EOKwNxcBYkrW6iIDs8Thn9Nl8zdP3HFVlxwaNV24uFmk1vkKI4xreAkJ9Aa1L6/hHB3EI6WrA=
    distributions: bdist_wheel sdist
    skip_existing: true
    skip_cleanup: true
    on:
      repo: arthuro555/pokemonlib
      branch: release
      python: 3.7
  - provider: releases
    api_key:
      secure: c9QGhPbFy0k+BkitBwPGqe79b2HLbyFZpBQjLsggS6BpHUe5qPLM9CRQV9SYd2kOMipuTGoKJRFo+JMmgP9Hf++nspKr7FcEHdn7HwQTwPJIhDoAp+ircZOJLNA8iP28W4wW3PYKPKZuX8nJFWcsh7/e+gSFFkl9Mb5JS/uzxW7JTjXawEBpC9rSKw5MYrcn0mvrN/M/Z/tTbT0NKfKZcmF4in/XCZHNDSD5EBhnnXNRZ3evFuXZFTSSvKwnYjwiwD9Vo53TDkd17B1kHwcoo9/c+okitIJmMDBTwSaWv7x8YkL5BYYhJ1dL+bCOTCZnIUY1RxIDb5T6f8TaWN3Ty2PRjZSKmw5yj/XjGLrtTMGRmuDzxo3Ao3HK5LgjgD0Zqh0QIvIlgWSuUJw56FnfzD5JDmStcA/ypyyPOvBaH5hH2dzcOPy5hHP3cuwrleUtupD9+F8ZbLeWkxqzWTczQjpujqOXyaYYXeiA+zaMtOUVKdJfj+rNEGXRXHN+hpPKbjVXouvjoP3LxnP0Q6EudO/Ck/+vpMjac8Dr4OI+ed2W+CuQSIrCIQIJ64DTDJNVQGT5a+JQxaqxfAVV3U3jjpxRBb32ht0sP9Wptcz2+BednbCoTyxbE/5sw9JvpKiV13fXORE8wRBB1RIHdeQ84aEXSM4+tv9grkiY7UXyBIs=
    file: dist/pokemonlib-*.tar.gz
    skip_cleanup: true
    on:
      repo: arthuro555/pokemonlib
      branch: release
      python: 3.7
after_deploy:
  - rm -rfv ./dist ./build